
//                            Copyright James P. McNellis 2011 - 2012.                            //
//                   Distributed under the Boost Software License, Version 1.0.                   //
//     (See accompanying file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)    //

// Note:  This file is generated by the build.  This empty file must be present in order to delay
// the C++ build until the CIL-to-C++ translation has completed.